#ifndef WEAPON_H
#define WEAPON_H

#include <iostream>
#include <vector>

using namespace std;

class weapon
{
public:

    string weapon_name = ""; // name of the given weapon
    int damage_out; // damage output of the weapon
    int heat_gen; // heat generated by the weapon
    float hit_chance; // chance that the weapon will hit a target before toHit modifier is applied
    int quantity; // number of weapons on a mech

    weapon(); // default constructor
    weapon(string); // constructs weapon with a filename used to populate its weapon specs
    ~weapon(); // deconstructor

    void pop_weapon_specs(string); // helper function that populated the weapon_name, damage_out, heat_gen, and hit_chance variables from the provided file
    string get_weapon_name(); // returns the name of the weapon
    float get_weapon_hit_chance(); // returns the hit chance of the weapon
    int get_weapon_damage(); // returns the damage output of the weapon
    int get_weapon_heat(); // returns the heat generated by the weapon
    int get_weapon_quantity();// returns the number of weapons

};
#endif // MECH_H
